# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('main_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=200)),
                ('alt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='listing_provider',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('listing_agent', models.CharField(max_length=50)),
                ('agent_phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms_full', models.IntegerField()),
                ('square_feet', models.IntegerField()),
                ('square_feet_lot', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=99)),
                ('description', models.CharField(max_length=200)),
                ('home_type', models.CharField(max_length=50)),
                ('year_built', models.IntegerField()),
                ('price_per_square_foot', models.IntegerField()),
                ('date_posted', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('longitude', models.IntegerField()),
                ('latitude', models.IntegerField()),
                ('create_date', models.DateField()),
                ('original_url', models.CharField(max_length=100)),
                ('features', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='schools',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('main_id', models.IntegerField()),
                ('score', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('grades', models.CharField(max_length=100)),
                ('distance', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='listing_provider',
            name='main_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.Main'),
        ),
    ]
