# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_auto_20160415_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=350)),
                ('alt', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('grades', models.CharField(max_length=50)),
                ('distance', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.DeleteModel(
            name='images',
        ),
        migrations.RemoveField(
            model_name='listing_provider',
            name='main_id',
        ),
        migrations.DeleteModel(
            name='schools',
        ),
        migrations.AlterModelOptions(
            name='main',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='main',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='main',
            name='bathrooms_half',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='meta_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='meta_keywords',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='main',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='bathrooms_full',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='bedrooms',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='features',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='home_type',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='main',
            name='latitude',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='main',
            name='longitude',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='main',
            name='original_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='main',
            name='price_per_square_foot',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='square_feet_lot',
            field=models.CharField(max_length=30, verbose_name=b'Square Feet Lot'),
        ),
        migrations.AlterField(
            model_name='main',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='main',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='main',
            name='year_built',
            field=models.CharField(max_length=4, verbose_name=b'Year Built'),
        ),
        migrations.DeleteModel(
            name='listing_provider',
        ),
        migrations.AddField(
            model_name='school',
            name='main',
            field=models.ForeignKey(db_column=b'main_id', on_delete=django.db.models.deletion.CASCADE, related_name='school', to='realestate.Main'),
        ),
        migrations.AddField(
            model_name='image',
            name='main',
            field=models.ForeignKey(db_column=b'main_id', on_delete=django.db.models.deletion.CASCADE, related_name='image', to='realestate.Main'),
        ),
    ]
