# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='zip_code',
        ),
    ]
