# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0007_city_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainRemoved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_removed', models.DateField()),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='realestate.Main')),
            ],
        ),
    ]
