# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 22:28
from __future__ import unicode_literals

from django.db import migrations


CREATE_TRIGGER_FUNCTION = '''
CREATE OR REPLACE FUNCTION save_property_as_unavailable() RETURNS TRIGGER AS
$BODY$
BEGIN
    INSERT INTO
        realestate_mainremoved(main_id, date_removed)
        VALUES(new.id,now());

           RETURN new;
END;
$BODY$
language plpgsql;
'''

CREATE_TRIGGER_ITSELF = '''
CREATE TRIGGER on_property_unavailable
    AFTER UPDATE ON main
    FOR EACH ROW
    WHEN (NEW.available = FALSE)
    EXECUTE PROCEDURE save_property_as_unavailable();
'''


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0008_mainremoved'),
    ]

    operations = [
        migrations.RunSQL(CREATE_TRIGGER_FUNCTION),
        migrations.RunSQL(CREATE_TRIGGER_ITSELF)
    ]
