# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 14:59
from __future__ import unicode_literals

from django.db import migrations


CREATE_TRIGGER_FUNCTION = '''
CREATE OR REPLACE FUNCTION save_property_as_unavailable() RETURNS TRIGGER AS
$BODY$
BEGIN
    INSERT INTO
        realestate_mainremoved(main_id, date_removed)
        VALUES(new.id,NOW() at time zone 'utc 8');

           RETURN new;
END;
$BODY$
language plpgsql;
'''


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0009_auto_20160509_2228'),
    ]

    operations = [
        migrations.RunSQL(CREATE_TRIGGER_FUNCTION),
    ]
