# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0010_auto_20160510_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'', verbose_name=b'Image')),
                ('main', models.ForeignKey(db_column=b'main_id', on_delete=django.db.models.deletion.CASCADE, related_name='local_image', to='realestate.Main')),
            ],
            options={
                'db_table': 'main_image',
            },
        ),
    ]
