# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import realestate.models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0011_mainimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainimage',
            name='image',
            field=models.ImageField(upload_to=realestate.models.image_path, verbose_name=b'Image'),
        ),
    ]
