# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0013_auto_20160525_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='main',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
