# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0014_auto_20160525_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
