# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0017_auto_20160526_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
