# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 19:17
from __future__ import unicode_literals

from django.db import migrations
import realestate.custom_models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0018_auto_20160526_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='price',
            field=realestate.custom_models.CustomMoneyField(max_length=20),
        ),
    ]
